/*
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
 */

function generateTriangleNumbers() {
    var number = 0;
    for(var i = 1; i < 100000000; i++) {
        number += i;
        if(divisorsCheck(number, 500)) {
            return number;
        }
    }
    return -1;
}

/**
 * @param number: a number to be checked for the number of divisors
 * @param n: minimum number of divisors required to pass the test
 */
function divisorsCheck(number, n) {
    var divisorsCount = 1;
    var sqrt = Math.sqrt(number); // optimization (1)
    for(var i = 2; i <= sqrt; i++) {
       if(number % i === 0)
           divisorsCount++;
    }
    divisorsCount = divisorsCount * 2; // optimization (1)
    if(sqrt % 1 === 0) divisorsCount--; // optimization (1)
    return divisorsCount > n;
}

console.log(generateTriangleNumbers());
// 76576500