// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


const someDivisorFiboSum = (divisor, Limit) =>{
    let firstFiboElement = 1, secondFiboElement = 1;
    let buf;
    let accum = 0;
    while (secondFiboElement < Limit){
        if (secondFiboElement % divisor === 0){
            accum += secondFiboElement;
        }
        buf = firstFiboElement;
        firstFiboElement = secondFiboElement;
        secondFiboElement = nextFibonacci(buf, secondFiboElement);
    }
    return accum;
};

const nextFibonacci = (prePrev, prev) => {
    return prePrev + prev;
};


console.time('1');
console.log(someDivisorFiboSum(2, 4000000));
console.timeEnd('1');

